const WEB = {
  id: "web",
  primary: "var(--brand-primary)",
  secondary: "var(--cyan)",
  accent: "var(--brand-accent)",
  glowA: "color-mix(in srgb, var(--cyan) 22%, transparent)",
  glowB: "color-mix(in srgb, var(--brand-primary) 16%, transparent)",
  pillBg: "color-mix(in srgb, var(--cyan) 12%, transparent)",
  pillBorder: "color-mix(in srgb, var(--cyan) 32%, transparent)",
  chips: ["Fast", "SEO Ready", "Secure"],
};

const THEMES = {
  web: WEB,
  "web development": WEB,
  mobile: {
    id: "mobile",
    primary: "var(--brand-primary)",
    secondary: "var(--cyan)",
    accent: "var(--brand-accent)",
    glowA: "color-mix(in srgb, var(--cyan) 22%, transparent)",
    glowB: "color-mix(in srgb, var(--brand-primary) 14%, transparent)",
    pillBg: "color-mix(in srgb, var(--cyan) 12%, transparent)",
    pillBorder: "color-mix(in srgb, var(--cyan) 34%, transparent)",
    chips: ["Seamless UX", "High Performance", "Secure & Scalable"],
  },
  "mobile engineering": {
    id: "mobile",
    primary: "var(--brand-primary)",
    secondary: "var(--cyan)",
    accent: "var(--brand-accent)",
    glowA: "color-mix(in srgb, var(--cyan) 22%, transparent)",
    glowB: "color-mix(in srgb, var(--brand-primary) 14%, transparent)",
    pillBg: "color-mix(in srgb, var(--cyan) 12%, transparent)",
    pillBorder: "color-mix(in srgb, var(--cyan) 34%, transparent)",
    chips: ["Seamless UX", "High Performance", "Secure & Scalable"],
  },
  ai: {
    id: "ai",
    primary: "var(--navy)",
    secondary: "var(--cyan)",
    accent: "var(--brand-accent)",
    support: "var(--brand-primary)",
    glowA: "color-mix(in srgb, var(--cyan) 22%, transparent)",
    glowB: "color-mix(in srgb, var(--brand-accent) 14%, transparent)",
    pillBg: "color-mix(in srgb, var(--cyan) 12%, transparent)",
    pillBorder: "color-mix(in srgb, var(--cyan) 34%, transparent)",
    chips: ["AI Automation", "Smart Insights"],
  },
  "artificial intelligence": {
    id: "ai",
    primary: "var(--navy)",
    secondary: "var(--cyan)",
    accent: "var(--brand-accent)",
    support: "var(--brand-primary)",
    glowA: "color-mix(in srgb, var(--cyan) 22%, transparent)",
    glowB: "color-mix(in srgb, var(--brand-accent) 14%, transparent)",
    pillBg: "color-mix(in srgb, var(--cyan) 12%, transparent)",
    pillBorder: "color-mix(in srgb, var(--cyan) 34%, transparent)",
    chips: ["AI Automation", "Smart Insights"],
  },
  growth: {
    id: "growth",
    primary: "var(--brand-primary)",
    secondary: "var(--brand-accent)",
    accent: "var(--cyan)",
    glowA: "color-mix(in srgb, var(--brand-accent) 18%, transparent)",
    glowB: "color-mix(in srgb, var(--cyan) 16%, transparent)",
    pillBg: "color-mix(in srgb, var(--brand-accent) 12%, transparent)",
    pillBorder: "color-mix(in srgb, var(--brand-accent) 32%, transparent)",
    chips: ["Higher Conversion", "Campaign Performance"],
  },
  "digital growth": {
    id: "growth",
    primary: "var(--brand-primary)",
    secondary: "var(--brand-accent)",
    accent: "var(--cyan)",
    glowA: "color-mix(in srgb, var(--brand-accent) 18%, transparent)",
    glowB: "color-mix(in srgb, var(--cyan) 16%, transparent)",
    pillBg: "color-mix(in srgb, var(--brand-accent) 12%, transparent)",
    pillBorder: "color-mix(in srgb, var(--brand-accent) 32%, transparent)",
    chips: ["Higher Conversion", "Campaign Performance"],
  },
  "digital marketing": {
    id: "growth",
    primary: "var(--brand-primary)",
    secondary: "var(--brand-accent)",
    accent: "var(--cyan)",
    glowA: "color-mix(in srgb, var(--brand-accent) 18%, transparent)",
    glowB: "color-mix(in srgb, var(--cyan) 16%, transparent)",
    pillBg: "color-mix(in srgb, var(--brand-accent) 12%, transparent)",
    pillBorder: "color-mix(in srgb, var(--brand-accent) 32%, transparent)",
    chips: ["Higher Conversion", "Campaign Performance"],
  },
  cloud: {
    id: "cloud",
    primary: "var(--navy)",
    secondary: "var(--brand-primary)",
    accent: "var(--brand-accent)",
    support: "var(--cyan)",
    glowA: "color-mix(in srgb, var(--brand-primary) 20%, transparent)",
    glowB: "color-mix(in srgb, var(--cyan) 16%, transparent)",
    pillBg: "color-mix(in srgb, var(--brand-primary) 12%, transparent)",
    pillBorder: "color-mix(in srgb, var(--brand-primary) 32%, transparent)",
    chips: ["High Availability", "Auto Scaling", "Secure Architecture"],
  },
  "cloud infrastructure": {
    id: "cloud",
    primary: "var(--navy)",
    secondary: "var(--brand-primary)",
    accent: "var(--brand-accent)",
    support: "var(--cyan)",
    glowA: "color-mix(in srgb, var(--brand-primary) 20%, transparent)",
    glowB: "color-mix(in srgb, var(--cyan) 16%, transparent)",
    pillBg: "color-mix(in srgb, var(--brand-primary) 12%, transparent)",
    pillBorder: "color-mix(in srgb, var(--brand-primary) 32%, transparent)",
    chips: ["High Availability", "Auto Scaling", "Secure Architecture"],
  },
};

export function getHeroTheme(tag = "") {
  const key = String(tag).trim().toLowerCase();
  return THEMES[key] || WEB;
}
